### ISSUE TITLE
Does not appear to work on Apple Silicon running Ventura

### ISSUE THREAD

**Issue by gahbes** [Vargol/spatial-media#10]
spatialmedia % python gui.py
Traceback (most recent call last):
  File "gui.py", line 48, in <module>
    from spatialmedia import metadata_utils 
  File "../spatialmedia/__init__.py", line 25, in <module>
    import spatialmedia.metadata_utils
  File "../spatialmedia/metadata_utils.py", line 27, in <module>
    from spatialmedia import mpeg
  File "../spatialmedia/mpeg/__init__.py", line 20, in <module>
    import spatialmedia.mpeg.sv3d
  File "../spatialmedia/mpeg/sv3d.py", line 28, in <module>
    from spatialmedia.mpeg import mesh_projection
  File "../spatialmedia/mpeg/mesh_projection.py", line 31, in <module>
    from spatialmedia.mpeg import mesh
  File "../spatialmedia/mpeg/mesh.py", line 27, in <module>
    from spatialmedia import metadata_utils
ImportError: cannot import name metadata_utils

**Comment by Vargol** [comment]
Hi, what version of python are you using, I works on Big sur and Sonoma with python 3.10 so it may be a change in the way python does its imports are triggering an issue in the code.

```
File "../spatialmedia/mpeg/mesh.py", line 27, in
from spatialmedia import metadata_utils
```

Try commenting that line out. If you don't know any python just stick a  # at the start  of the line so  if becomes

```
#from spatialmedia import metadata_utils
```

I can't see why the import if there and a quick test also suggests its not needed and its creating a circular dependancy

**Comment by gahbes** [comment]
Thanks, I was trying with Python 2.7 which was required by the old Google injector. With python 3 and tkinter it works.
